### ISSUE TITLE
aco-shioya-00.pdfについて

### ISSUE THREAD

**Issue by kiszk** [shioyadan/advanced-computer-organization#1]
本論と関係ないtypoですが、[P3](https://github.com/shioyadan/advanced-computer-organization/blob/master/aco-shioya-00.pdf)のタイトルは、「構正論」->「構成論」ではないでしょうか。

**Comment by shioyadan** [comment]
これもその通りですね．
なんで正になっていたのか謎です…

**Comment by kiszk** [comment]
ありがとうございます。なぜか、"構" + "正論" で切れてしまったのでしょうか。
