### ISSUE TITLE
aco-shioya-appendix-processorのレジスタ表記

### ISSUE THREAD

**Issue by kiszk** [shioyadan/advanced-computer-organization#2]
[P47-50](https://github.com/shioyadan/advanced-computer-organization/blob/master/aco-shioya-appendix-processor.pdf)、P104で
- I2のsrcオペランドが、x20のまま論理レジスタになっています。他に合わせるとp20でしょうか？
- I2のdstオペランドは、それ以降のページに合わせると、p24でしょうか？

P45のI2のsrcオペランドがx11のまま論理レジスタになっています。他に合わせると、p11など、でしょうか？

**Comment by shioyadan** [comment]
ありがとうございます．
確認しましたが，思いっきり間違ってました… ご指摘の通りです．
直しておきます．

**Comment by kiszk** [comment]
P50のI2が、x20のままのようです。

**Comment by shioyadan** [comment]
こちらも直しました．何度もスイマセン．
