### ISSUE TITLE
aco-shioya-appendix-bpredのBATAGE

### ISSUE THREAD

**Issue by kiszk** [shioyadan/advanced-computer-organization#4]
[P53](https://github.com/shioyadan/advanced-computer-organization/blob/master/aco-shioya-appendix-bpred.pdf)の説明中、「down 0→」は「down 0→2」ではないでしょうか。

**Comment by shioyadan** [comment]
ここも直しておきました．ありがとうございます．

今読み返すと，ちょっとこのあたりは資料を読んだだけでは何を言っているのか分からないかもしれないと思ったのですが，内容に関する質問等ある場合も遠慮なく書いていただければと思います．
